---
image: "crazymax/msmtpd:latest"
host:
  name: "msmtpd"
  FQDN: "smtp.gmail.com"
  port: "587"
replicas: 1
from: "foo@gmail.com"
TLS: "on"
startTLS: "on"
TLSchecker: "on"
auth: "on"

credentials:
  email:
    user: "foo"
    password: "bar"   
