---
enable: true

image: "crazymax/msmtpd:latest"
replicas: "1"
host:
  name: "msmtpd"
  FQDN: "smtp.gmail.com"
  port: "587"
from: "foo@gmail.com"
TLS: "on"
startTLS: "on"
TLSchecker: "on"
auth: "on"

credentials:
  email:
    user: "foo"
    password: "bar"   
