---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.host.name }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.application.host.name }}
  ports:
    - name: {{ .Values.application.host.name }}
      protocol: TCP
      port: 8000
      targetPort: {{ .Values.application.host.name }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.host.name }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: {{ .Values.application.host.name }}
spec:
  replicas: {{ .Values.application.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.application.host.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.application.host.name }}
    spec:
      hostname: {{ .Values.application.host.name }}
      restartPolicy: Always
      containers:
        - name: {{ .Values.application.host.name }}
          image: {{ .Values.application.image | quote }}
          envFrom:
            - configMapRef:
                name: librenms-cfg
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_password
            - name: LIBRENMS_BASE_URL
              value: {{ .Values.application.baseURL | quote }}
            - name: LIBRENMS_WEATHERMAP
              value: {{ .Values.application.weathermap.enable | quote }}
            - name: LIBRENMS_WEATHERMAP_SCHEDULE
              value: {{ .Values.application.weathermap.schedule | quote }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          ports:
            - name: {{ .Values.application.host.name }}
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: xmatters-transport-file
              mountPath: /opt/librenms/LibreNMS/Alert/Transport/Xmatters.php
              subPath: Xmatters.php
            - name: application
              mountPath: /data
      volumes:
        - name: xmatters-transport-file
          configMap:
            name: xmatters-transport-file
        - name: application
          persistentVolumeClaim:
            claimName: application

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: application
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: application
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.application.host.volumeSize }}
  volumeName: "{{ .Release.Name }}-application"

