---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms-cfg
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  TZ: {{ .Values.global.TZ | quote }}
  PUID: {{ .Values.global.puid | quote }}
  PGID: {{ .Values.global.pgid | quote }}
  REAL_IP_FROM: {{ .Values.application.realIPfrom | quote }}
  REAL_IP_HEADER: {{ .Values.application.realIPheader | quote }}
  LOG_IP_VAR: {{ .Values.application.logIP | quote }}
  UPLOAD_MAX_SIZE: {{ .Values.application.uploadMAXsize | quote }}
  MEMORY_LIMIT: {{ .Values.application.MemoryLimit | quote }}
  OPCACHE_MEM_SIZE: {{ .Values.application.opcacheMEMsize | quote }}
  DB_HOST: "database"
  DB_NAME: {{ .Values.mariadb.database  | quote }}
  DB_TIMEOUT: {{ .Values.mariadb.timeout  | quote }}
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  MEMCACHED_HOST: "memcached"
  MEMCACHED_PORT: "11211"
  RRDCACHED_SERVER: "rrdcached:42217"
  LIBRENMS_SNMP_COMMUNITY: {{ .Values.application.SNMPcommunity | quote }}
  mysql_user: {{ .Values.mariadb.credentials.user | quote }}
  mysql_password: {{ .Values.mariadb.credentials.password | quote }}
  mysql_root: {{ .Values.mariadb.credentials.rootPassword | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-file
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  config.php: |-
    <?php
    $config['enable_syslog'] =                      {{ .Values.application.syslogng.enable | quote }};
    $config['syslog_purge'] =                       {{ .Values.application.syslogng.purge | quote }};

    $config['enable_billing'] =                     {{ .Values.application.billing.enable | quote }};
    $config['billing_data_purge'] =                 {{ .Values.application.billing.purge | quote }};
    $config['billing']['95th_default_agg'] =        {{ .Values.application.billing.default95 | quote }};

    $config['customers_descr'][] =                  {{ .Values.application.parsing.customers | quote }};
    $config['transit_descr'][] =                    {{ .Values.application.parsing.transit | quote }};
    $config['peering_descr'][] =                    {{ .Values.application.parsing.peering | quote }};
    $config['core_descr'][] =                       {{ .Values.application.parsing.core | quote }};

    $config['oxidized.enabled'][] =                 {{ .Values.oxidized.enable | quote }};
    $config['oxidized']['url'] =                    "http://oxidized:8888";
    $config['oxidized']['default_group'] =          'other';
    $config['oxidized']['features']['versioning'] = {{ .Values.oxidized.featureVers | quote }};
    $config['oxidized']['group_support'] =          {{ .Values.oxidized.groupSupport | quote }};
    $config['oxidized']['reload_nodes'] =           {{ .Values.oxidized.reloadNodes | quote }};


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smokeping-file
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  librenms-smokeping: |-
    /opt/librenms/lnms smokeping:generate --targets > /data/smokeping/config/librenms-targets.conf
    /opt/librenms/lnms smokeping:generate --probes  > /data/smokeping/config/librenms-probes.conf