---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms-cfg
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  TZ: {{ .Values.global.TZ | quote }}
  PUID: {{ .Values.global.puid | quote }}
  PGID: {{ .Values.global.pgid | quote }}
  REAL_IP_FROM: {{ .Values.shared.realIPfrom | quote }}
  REAL_IP_HEADER: {{ .Values.shared.realIPheader | quote }}
  LOG_IP_VAR: {{ .Values.shared.logIP | quote }}
  UPLOAD_MAX_SIZE: {{ .Values.shared.uploadMAXsize | quote }}
  MEMORY_LIMIT: {{ .Values.shared.MemoryLimit | quote }}
  OPCACHE_MEM_SIZE: {{ .Values.shared.opcacheMEMsize | quote }}
  DB_HOST: "database"
  DB_NAME: {{ .Values.mariadb.database  | quote }}
  DB_TIMEOUT: {{ .Values.mariadb.timeout  | quote }}
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  MEMCACHED_HOST: "memcached"
  MEMCACHED_PORT: "11211"
  RRDCACHED_SERVER: "rrdcached:42217"
  LIBRENMS_SNMP_COMMUNITY: {{ .Values.application.SNMPcommunity | quote }}
  mysql_user: {{ .Values.mariadb.credentials.user | quote }}
  mysql_password: {{ .Values.mariadb.credentials.password | quote }}
  mysql_root: {{ .Values.mariadb.credentials.rootPassword | quote }}
