apiVersion: batch/v1
kind: Job
metadata:
  name: depl-basic
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  template:
    spec:
      containers:
      - name: depl-basic
        image: {{ .Values.application.image | quote }}
        args:
          - /bin/sh 
          - "-c"
          - |
            su librenms 
            lnms config:set device_display_default '{{ "{{" }} $sysName_fallback }}';
            lnms config:set enable_syslog {{ .Values.application.syslogng.enable | quote }};
            lnms config:set enable_billing {{ .Values.application.billing.enable | quote }};
            lnms config:set snmp.community {{ .Values.application.SNMPcommunity }};
            lnms config:set billing_data_purge {{ .Values.application.billing.purge | quote }};
            lnms config:set billing.95th_default_agg {{ .Values.application.billing.default95 | quote }};
            lnms config:set customers_descr.+ {{ .Values.application.parsing.customers | quote }};
            lnms config:set transit_descr.+ {{ .Values.application.parsing.transit | quote }};
            lnms config:set peering_descr.+ {{ .Values.application.parsing.peering | quote }};
            lnms config:set core_descr.+ {{ .Values.application.parsing.core | quote }};
        env:
          - name: DB_HOST
            value: "database"
          - name: DB_NAME 
            value: {{ .Values.mariadb.database | quote }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: mysql_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: mysql_password
      restartPolicy: Never
  backoffLimit: 4