---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dispatcher
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: dispatcher
spec:
  serviceName: dispatcher
  replicas: {{ .Values.application.dispatcher.replicas }}
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      hostname: {{ .Release.Name }}-dispatcher
      restartPolicy: Always
      containers:
        - name: dispatcher
          image: {{ .Values.application.image | quote }}
          envFrom:
            - configMapRef:
                name: librenms-cfg
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_password
            - name: DISPATCHER_ARGS
              value: {{ .Values.application.dispatcher.args | quote }}
            - name: SIDECAR_DISPATCHER
              value: "1"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - name: config-file
              mountPath: /data/config/config.php
              subPath: config.php
            - name: xmatters-transport-file
              mountPath: /opt/librenms/LibreNMS/Alert/Transport/Xmatters.php
              subPath: Xmatters.php
            - name: application
              mountPath: /data
      volumes:
        - name: config-file
          configMap:
            name: config-file
        - name: xmatters-transport-file
          configMap:
            name: xmatters-transport-file
        - name: application
          persistentVolumeClaim:
            claimName: application
