---
apiVersion: batch/v1
kind: Job
metadata:
  name: depl-oxidized
  namespace: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  template:
    spec:
      containers:
      - name: depl-oxidized
        image: {{ .Values.application.image | quote }}
        args:
          - /bin/sh 
          - "-c"
          - |
            su librenms 
            lnms config:set oxidized.url "http://oxidized:8888"
            # Basic config
            lnms config:set oxidized.enabled              {{ .Values.oxidized.enable | quote }}
            lnms config:set oxidized.default_group        {{ .Values.oxidized.default_group | quote }}
            lnms config:set oxidized.features.versioning  {{ .Values.oxidized.featureVers | quote }}
            lnms config:set oxidized.group_support        {{ .Values.oxidized.groupSupport | quote }}
            lnms config:set oxidized.reload_nodes         {{ .Values.oxidized.reloadNodes | quote }}
            # Ignore devices
            lnms config:set oxidized.ignore_os            '{{ .Values.oxidized.ignore.os | toJson }}' --ignore-checks
            lnms config:set oxidized.ignore_types         '{{ .Values.oxidized.ignore.types | toJson }}' --ignore-checks
            lnms config:set oxidized.ignore_groups        '{{ .Values.oxidized.ignore.groups | toJson }}' --ignore-checks
            # Create special groups groups:
            lnms config:set oxidized.maps.group.purpose.1 '{"regex": {{ .Values.oxidized.group.one.string | quote }}, "value": "One"}' --ignore-checks
            lnms config:set oxidized.maps.group.purpose.2 '{"regex": {{ .Values.oxidized.group.two.string | quote }}, "value": "Two"}' --ignore-checks
            lnms config:set oxidized.maps.group.purpose.3 '{"regex": {{ .Values.oxidized.group.three.string | quote }}, "value": "Three"}' --ignore-checks
            lnms config:set oxidized.maps.group.purpose.4 '{"regex": {{ .Values.oxidized.group.four.string | quote }}, "value": "Four"}' --ignore-checks
            lnms config:set oxidized.maps.group.purpose.5 '{"regex": {{ .Values.oxidized.group.five.string | quote }}, "value": "Five"}' --ignore-checks
            lnms config:set oxidized.maps.group.notes.1 '{"regex": {{ .Values.oxidized.group.one.string | quote }}, "value": "One"}' --ignore-checks
            lnms config:set oxidized.maps.group.notes.2 '{"regex": {{ .Values.oxidized.group.two.string | quote }}, "value": "Two"}' --ignore-checks
            lnms config:set oxidized.maps.group.notes.3 '{"regex": {{ .Values.oxidized.group.three.string | quote }}, "value": "Three"}' --ignore-checks
            lnms config:set oxidized.maps.group.notes.4 '{"regex": {{ .Values.oxidized.group.four.string | quote }}, "value": "Four"}' --ignore-checks
            lnms config:set oxidized.maps.group.notes.5 '{"regex": {{ .Values.oxidized.group.five.string | quote }}, "value": "Five"}' --ignore-checks
        env:
          - name: DB_HOST
            value: "database"
          - name: DB_NAME 
            value: {{ .Values.mariadb.database | quote }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: mysql_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: mysql_password
      restartPolicy: Never
  backoffLimit: 4
