---
apiVersion: batch/v1
kind: Job
metadata:
  name: depl-basic
  namespace: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  template:
    spec:
      containers:
      - name: depl-basic
        image: {{ .Values.application.image | quote }}
        args:
          - /bin/sh 
          - "-c"
          - |
            su librenms 
            lnms config:set device_display_default    '{{ "{{" }} $sysName_fallback }}'
            lnms config:set snmp.community            '{{ .Values.application.SNMPcommunity | toJson }}'
            lnms config:set webui.graph_type          {{ .Values.application.lnms.graphs.type | quote }}
            lnms config:set webui.dynamic_graphs      {{ .Values.application.lnms.graphs.dynamic | quote }}
            lnms config:set enable_syslog             {{ .Values.application.syslogng.enable | quote }}
            lnms config:set syslog_purge              {{ .Values.application.syslogng.purge | quote }}
            # Billing;
            lnms config:set enable_billing            {{ .Values.application.lnms.billing.enable | quote }}
            # Parsing;
            lnms config:set customers_descr.2         {{ .Values.application.lnms.parsing.customers | quote }}
            lnms config:set transit_descr.2           {{ .Values.application.lnms.parsing.transit | quote }}
            lnms config:set peering_descr.2           {{ .Values.application.lnms.parsing.peering | quote }}
            lnms config:set core_descr.2              {{ .Values.application.lnms.parsing.core | quote }}
        env:
          - name: DB_HOST
            value: "database"
          - name: DB_NAME 
            value: {{ .Values.mariadb.database | quote }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: mysql_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: mysql_password
      restartPolicy: Never
  backoffLimit: 4

---
apiVersion: batch/v1
kind: Job
metadata:
  name: depl-oxidized
  namespace: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  template:
    spec:
      containers:
      - name: depl-oxidized
        image: {{ .Values.application.image | quote }}
        args:
          - /bin/sh 
          - "-c"
          - |
            su librenms 
            lnms config:set oxidized.url "http://oxidized:8888"
            # Basic config
            lnms config:set oxidized.enabled.+            {{ .Values.oxidized.enable | quote }}
            lnms config:set oxidized.default_group        {{ .Values.oxidized.default_group | quote }}
            lnms config:set oxidized.features.versioning  {{ .Values.oxidized.featureVers | quote }}
            lnms config:set oxidized.group_support        {{ .Values.oxidized.groupSupport | quote }}
            lnms config:set oxidized.reload_nodes         {{ .Values.oxidized.reloadNodes | quote }}
            # Ignore devices
            lnms config:set oxidized.ignore_os            {{ .Values.oxidized.ignore.os | quote }}
            lnms config:set oxidized.ignore_types         {{ .Values.oxidized.ignore.types | quote }}
            lnms config:set oxidized.ignore_groups       {{ .Values.oxidized.ignore.groups | quote }}
            # Create special groups groups:
            #lnms config:set oxidized.maps.group.purpose.1 '{"regex": {{ .Values.oxidized.group.one.string | quote }}, "value": "One"}'
            #lnms config:set oxidized.maps.group.purpose.2 '{"regex": {{ .Values.oxidized.group.two.string | quote }}, "value": "Two"}'
            #lnms config:set oxidized.maps.group.purpose.3 '{"regex": {{ .Values.oxidized.group.three.string | quote }}, "value": "Three"}'
            #lnms config:set oxidized.maps.group.purpose.4 '{"regex": {{ .Values.oxidized.group.four.string | quote }}, "value": "Four"}'
            #lnms config:set oxidized.maps.group.purpose.5 '{"regex": {{ .Values.oxidized.group.five.string | quote }}, "value": "Five"}'
            #lnms config:set oxidized.maps.group.notes.1 '{"regex": {{ .Values.oxidized.group.one.string | quote }}, "value": "One"}'
            #lnms config:set oxidized.maps.group.notes.2 '{"regex": {{ .Values.oxidized.group.two.string | quote }}, "value": "Two"}'
            #lnms config:set oxidized.maps.group.notes.3 '{"regex": {{ .Values.oxidized.group.three.string | quote }}, "value": "Three"}'
            #lnms config:set oxidized.maps.group.notes.4 '{"regex": {{ .Values.oxidized.group.four.string | quote }}, "value": "Four"}'
            #lnms config:set oxidized.maps.group.notes.5 '{"regex": {{ .Values.oxidized.group.five.string | quote }}, "value": "Five"}'
        env:
          - name: DB_HOST
            value: "database"
          - name: DB_NAME 
            value: {{ .Values.mariadb.database | quote }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: mysql_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: mysql_password
      restartPolicy: Never
  backoffLimit: 4
