---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-applicaton"
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: {{ .Values.application.host.FQDN | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: application
            port:
              number: 8000
  - host: {{ .Values.smokeping.host.FQDN | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smokeping
            port:
              number: 8081
  - host: {{ .Values.oxidized.host.FQDN | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oxidized
            port:
              number: 8888
  - host: "*"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: application
            port:
              number: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-syslog-tcp"
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: syslogng
  ports:
    - name: syslog-tcp
      protocol: TCP
      port: 514
      targetPort: syslog-tcp

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-syslog-udp"
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: syslogng
  ports:
    - name: syslog-udp
      protocol: UDP
      port: 514
      targetPort: syslog-udp

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-snmptrapd-tcp"
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: snmptrapd
  ports:
    - name: snmptrapd-tcp
      protocol: TCP
      port: 162
      targetPort: snmptrapd-tcp

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-snmptrapd-udp"
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: snmptrapd
  ports:
    - name: snmptrapd-udp
      protocol: UDP
      port: 162
      targetPort: snmptrapd-udp
      