---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-database"
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    type: storage
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.mariadb.host.volumeSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.storage.path }}{{ .Release.Name }}/database"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-application"
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    type: storage
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.application.host.volumeSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.storage.path }}{{ .Release.Name }}/application"
