---
apiVersion: batch/v1
kind: Job
metadata:
  name: lnms
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: dispatcher
spec:
  template:
    spec:
      containers:
      - name: lnms 
        image: {{ .Values.application.image | quote }}
        command: 
        - /user/bin/lnms config:set email_user XXX

        envFrom:
          - configMapRef:
              name: librenms-cfg
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: mysql_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: mysql_password
      restartPolicy: Never
  backoffLimit: 4