apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
type: Opaque
data:
  mysql_user: {{ .Values.mariadb.credentials.user | b64enc | quote }}
  mysql_password: {{ .Values.mariadb.credentials.password | b64enc | quote }}
  mysql_root: {{ .Values.mariadb.credentials.rootPassword | b64enc | quote }}
  redis_password: {{ .Values.redis.credentials.password | b64enc | quote }}
  email_user: {{ .Values.msmtpd.credentials.email.user | b64enc | quote }}
  email_password: {{ .Values.msmtpd.credentials.email.password  | b64enc | quote }}
