---
{{- if .Values.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.syslogng.name | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.application.syslogng.name | quote }}
  ports:
    - name: syslog-tcp
      protocol: TCP
      port: 514
      targetPort: 514
    - name: syslog-udp
      protocol: UDP
      port: 514
      targetPort: 514

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.application.syslogng.name | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: {{ .Values.application.syslogng.name | quote }}
spec:
  serviceName: {{ .Values.application.syslogng.name | quote }}
  replicas: {{ .Values.application.syslogng.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.application.syslogng.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.syslogng.name | quote }}
    spec:
      hostname: {{.Release.Name}}-syslogng
      restartPolicy: Always
      containers:
        - name: {{ .Values.application.syslogng.name | quote }}
          image: {{ .Values.application.image | quote }}
          envFrom:
            - configMapRef:
                name: librenms-cfg
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_password
            - name: SIDECAR_SYSLOGNG
              value: "1"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          ports:
            - name: syslog-tcp
              containerPort: 514
              protocol: TCP
            - name: syslog-udp
              containerPort: 514
              protocol: UDP                
          volumeMounts:
            - name: application
              mountPath: /data
      volumes:
        - name: application
          persistentVolumeClaim:
            claimName: application
{{- end }}