---
apiVersion: v1
kind: Service
metadata:
  name: syslogng
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: syslogng
  ports:
    - name: syslog-tcp
      protocol: TCP
      port: 514
      targetPort: 514
    - name: syslog-udp
      protocol: UDP
      port: 514
      targetPort: 514

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syslogng
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: syslogng
spec:
  serviceName: syslogng
  replicas: 1
  selector:
    matchLabels:
      app: syslogng
  template:
    metadata:
      labels:
        app: syslogng
    spec:
      hostname: {{.Release.Name}}-syslogng
      restartPolicy: Always
      containers:
        - name: syslogng
          image: {{.Values.librenms.image}}
          envFrom:
            - configMapRef:
                name: librenms-cfg
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_password
            - name: LIBRENMS_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-sec
                  key: redis_password          
            - name: SIDECAR_SYSLOGNG
              value: "1"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          ports:
            - name: syslog-tcp
              containerPort: 514
              protocol: TCP
            - name: syslog-udp
              containerPort: 514
              protocol: UDP                
          volumeMounts:
            - name: rrdcached
              mountPath: /data
      volumes:
        - name: rrdcached
          persistentVolumeClaim:
            claimName: rrdcached-claim
