apiVersion: v2
appVersion: 1.0.1
description: A Helm chart for Kubernetes
name: librechart
type: application
version: 1.0.1

dependencies:
  - name: cert-manager
    version: "v1.14.0"
    condition: ingress.certManager.enabled
    repository: "https://charts.jetstack.io"
  - name: mariadb
    version: "*"
    condition: mariadb.enabled
    repository: "file://charts/mariadb"
  - name: redis
    version: "*"
    condition: redis.enabled
    repository: "file://charts/redis"
  - name: rrdcached
    version: "*"
    condition: rrdcached.enabled
    repository: "file://charts/rrdcached"
  - name: msmtpd
    version: "*"
    condition: msmtpd.enable
    repository: "file://charts/msmtpd"
  - name: oxidized
    version: "*"
    condition: oxidized.enable
    repository: "file://charts/oxidized"
  - name: smokeping
    version: "*"
    condition: smokeping.enable
    repository: "file://charts/smokeping"
  - name: xmatters
    version: "*"
    condition: xmatters.enable
    repository: "file://charts/xmatters"
