global:
  TZ: "Atlantic/Reykjavik"
  puid: "1000"
  pgid: "1000"
  company:
    name: "SENSA"  
    address: ""
    contact: ""

ingress:
  # befor you can enable hhtp you need to install a cert:
  # kubectl create secret tls https-cert --cert=<certificate-file> --key=<key-file> --namespace librenms
  https: false

mariadb:
  database: "librenms"
  host:
    name: "database"
    volumeSize: "20Gi"
  credentials:
    rootPassword: "fooRootPassword"
    user: "foo"
    password: "bar"

rrdcached:
  host:
    name: "lnms-rrdcached"
    port: "42217"

redis:
  lnms:
    host: "lnms-redis"
    port: "6379"
    database: "0"
    scheme: "tcp"
    cacheDriver: "redis"
    sessionDriver: "redis"

application:
  replicas: "1"
  image: "librenms/librenms:latest"
  host:
    FQDN: "nms.test.local"
    name: "lnms-app"
    realIPfrom: "0.0.0.0/32"
    realIPheader: "X-Forwarded-For" 
    volumeSize: "20Gi"
    baseURL: ""
  logIP: "remote_addr"
  nodePort: "30080"
  uploadMAXsize: "16M"
  SNMPcommunity: 
    - "community-string-1"
    - "community-string-2"
  dispatcher:
    name: "lnms-dispatcher"
    replicas: "1"
    nodeID: "poller 1"
    args: ""
  weathermap:
    enable: true
    schedule: "*/5 * * * *"
  syslogng:
    enable: true
    name: "lnms-syslog"
    replicas: "1"
    purge: "95"
  lnms:
    services:
      enable: false
    graphs:
      type: "svg"
      dynamic: true
    billing:
      enable: true
      purge: "95"
      default95: "1"
    parsing:
      customers: "c"
      transit: "t"
      peering: "p"
      core: "i"
  php:
    memoryLimit: "1024M"
    maxInputVars: "1000"
    opcacheMemSize: "256"

storage:
  path: "/opt/kubes/storage/"

xmatters:
  enable: false
  URL: "company.xmatters.com"
  APIkey: ""
  APIsecret: ""

msmtpd:
  enable: true
  host:
    name: "msmtpd"
    FQDN: "smtp.gmail.com"
    port: "587"
  from: "foo@gmail.com"
  credentials:
    email:
      user: "foo"
      password: "bar"   

oxidized:
  enable: true
  host:
    FQDN: "ox.test.local"
  credentials:
    token: "API-token-generated-inside-LIBRE"
  ignore:
    types: 
      - "server"
      - "power"
      - "storage"
    os: 
      - "linux"
      - "windows"
      - "ciscosb"
      - "jetdirect"
    groups:
      - ""
  # Device can be grouped by as string in the device NOTE or DESCRIPTION
  group:
    core:
      user: "deviceadmin"
      password: "devicepassword"
    one:
      user: ""
      password: ""
      string: "/^ox-group-1/"
    two:
      user: ""
      password: ""
      string: "/^ox-group-2/"
    three:
      password: ""
      pass: ""
      string: "/^ox-group-3/"
    four:
      password: ""
      pass: ""
      string: "/^ox-group-4/"
    five:
      user: ""
      password: ""
      string: "/^ox-group-5/"

smokeping:
  enable: false
  host:
    FQDN: "smokeping.test.local"
