---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rrdcached
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  TZ: {{ .Values.global.TZ | quote }}
  PUID: {{ .Values.global.puid | quote }}
  PGID: {{ .Values.global.pgid | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  WRITE_TIMEOUT: {{ .Values.writeTimeout | quote }}
  WRITE_JITTER: {{ .Values.writeJitter | quote }}
  WRITE_THREADS: {{ .Values.writeThreads | quote }}
  FLUSH_DEAD_DATA_INTERVAL: {{ .Values.flushDeadDataInterval | quote }}
