---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rrdcached
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  selector:
    app: rrdcached
  ports:
    - name: rrdcached
      protocol: TCP
      port: 42217
      targetPort: rrdcached

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}-rrdcached
  labels:
{{ include "common.labels" . | indent 4 }}
    app: rrdcached
spec:
  serviceName: rrdcached
  replicas: 1
  selector:
    matchLabels:
      app: rrdcached
  template:
    metadata:
      labels:
        app: rrdcached
    spec:
      hostname: {{.Release.Name}}-rrdcached
      restartPolicy: Always
      containers:
        - name: {{.Release.Name}}-rrdcached
          image: {{.Values.image}}
          envFrom:
            - configMapRef:
                name: rrdcached-cfg
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          ports:
            - name: rrdcached
              containerPort: 42217
              protocol: TCP
          volumeMounts:
            - name: {{.Release.Name}}-rrdcached
              mountPath: /data
      volumes:
        - name: {{.Release.Name}}-rrdcached
          persistentVolumeClaim:
            claimName: {{.Release.Name}}-rrdcached-claim
