---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.host.name | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  CONFIG_RELOAD_INTERVAL: {{ .Values.reloadInterval | quote }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oxidized-file
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  config: |-
    model: cisco
    resolve_dns: true
    interval: 72000
    use_syslog: false
    debug: false
    threads: 30
    use_max_threads: false
    timeout: 20
    retries: 3
    prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
    rest: 0.0.0.0:8888  
    next_adds_job: false
    vars: {}
    groups:
      core:
        username: {{ .Values.group.core.user }}
        password: {{ .Values.group.core.password }}
      one:
        username: {{ .Values.group.one.user }}
        password: {{ .Values.group.one.password }}
      two:
        username: {{ .Values.group.two.user }}
        password: {{ .Values.group.two.password }}
      three:
        username: {{ .Values.group.three.user }}
        password: {{ .Values.group.three.password }}
      four:
        username: {{ .Values.group.four.user }}
        password: {{ .Values.group.four.password }}
      five:
        username: {{ .Values.group.five.user }}
        password: {{ .Values.group.five.password }}
    models: {}
    model_map:
      juniper: junos
      cisco: ios
      cisco: iosxe
      mikrotik: routeros
      ubiquiti: airos
   
    pid: "/home/oxidized/.config/oxidized/pid"
    crash:
      directory: "/home/oxidized/.config/oxidized/crashes"
      hostnames: false
    stats:
      history_size: 10
    input:
      default: ssh, telnet
      debug: false
      ssh:
        secure: false
      ftp:
        passive: true
      utf8_encoded: true
    output:
      default: git
      git:
          user: Oxidized
          email: noc@sensa.is
          repo: "/home/oxidized/.config/oxidized/configs"
    source:
      default: http
      debug: false
      http:
        url: http://lnms-app:8000/api/v0/oxidized
        scheme: http
        secure: false
        map:
          name: hostname
          model: os
          group: group
          ip: ip
        headers:
          X-Auth-Token: {{ .Values.credentials.token }}
