---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oxidized
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  CONFIG_RELOAD_INTERVAL: {{ .Values.reloadInterval | quote }}
