{{- if and .Values.enabled .Values.certificate.create }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ default "https-cert" .Values.certificate.secretName | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ default "https-cert" .Values.certificate.secretName | quote }}
  issuerRef:
    kind: {{ default "ClusterIssuer" .Values.issuer.kind | quote }}
    name: {{ default "letsencrypt-prod" .Values.issuer.name | quote }}
  commonName: {{ .Values.certificate.commonName | quote }}
  dnsNames:
{{- range .Values.certificate.dnsNames }}
    - {{ . | quote }}
{{- end }}
{{- end }}
