---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.lnms.host | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.lnms.host | quote }}
  ports:
    - name: {{ .Values.lnms.host | quote }}
      protocol: TCP
      port: 6379
      targetPort: {{ .Values.lnms.host | quote }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.lnms.host | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: {{ .Values.lnms.host | quote }}
spec:
  serviceName: {{ .Values.lnms.host | quote }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.lnms.host | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.lnms.host | quote }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.lnms.host | quote }}
          image: {{.Values.image}}
          envFrom:
            - configMapRef:
                name: {{ .Values.lnms.host | quote }}
          ports:
            - name: {{ .Values.lnms.host | quote }}
              containerPort: 6379
