---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}-redis
  labels:
    app: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      hostname: {{.Release.Name}}-redis
      restartPolicy: Always
      containers:
        - name: {{.Release.Name}}-redis
          image: {{.Values.image}}
          envFrom:
            - configMapRef:
                name: redis-cfg
          env:
            - name: REDIS_REQUIRED_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-sec
                  key: redis_password
          ports:
            - name: redis
              containerPort: 6378
