apiVersion: v1
kind: Secret
metadata:
  name: redis-sec
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
type: Opaque
data:
  redis_password: {{ .Values.credentials.password | b64enc | quote }}
