---
{{- if .Values.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.host.name | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  selector:
    app: {{ .Values.host.name | quote }}
  ports:
    - name: {{ .Values.host.name | quote }}
      protocol: TCP
      port: 5000
      targetPort: {{ .Values.host.name | quote }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.host.name | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: {{ .Values.host.name | quote }}
spec:
  serviceName: {{ .Values.host.name | quote }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.host.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.host.name | quote }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.host.name | quote }}
          image: {{ .Values.image | quote }}
          envFrom:
            - configMapRef:
                name: {{ .Values.host.name | quote }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          ports:
            - name: {{ .Values.host.name | quote }}
              containerPort: 5000
              protocol: TCP
{{- end }}
