apiVersion: v2
appVersion: 1.0.0
description: A Helm chart for Kubernetes
name: librechart
type: application
version: 1.0.0

---
dependencies:
  - name: mariadb
    condition: mariadb.enabled
  - name: memcached
    condition: memcached.enabled
  - name: redis
    condition: redis.enabled
  - name: rrdcached
    condition: rrdcached.enabled
