---
global:
  TZ: "Atlantic/Reykjavik"
  puid: "1000"
  pgid: "1000"

shared:
  TZ: "Europe/London"
  puid: "1000"
  pgid: "1000"
  database: "libreDB2"
  realIPfrom: "0.0.0.0/32"
  realIPheader: "X-Forwarded-For"
  uploadMAXsize: "16M"
  MemoryLimit: "256M"
  opcacheMEMsize: "128"
  logIP: "remote_addr"

application:
  hostFQDN: "nms.test.local"
  replicas: "1"
  baseURL: ""
  SNMPcommunity: "test"
  nPort: "30080"
  weathermap: "false"
  weathermapSchedule: "*/5 * * * *"

dispatcher:
  replicas: "1"
  nodeID: "poller 1"
  args: ""

librenms:
  image: "librenms/librenms:latest"


## Services
mariadb:
  database: "librenms"
  storage:
    path: "/opt/kubes/storage/"
    size: "2Gi"
  credentials:
    rootPassword: "fooRootPassword"
    user: "foo"
    password: "bar"

redis:
  credentials:
    password: "bar"

msmtpd:
  host: "smtp.gmail.com"
  port: "587"
  from: "foo@gmail.com"
  credentials:
    email:
      user: "foo"
      password: "bar"   

rrdcached:
  storage:
    path: "/opt/kubes/storage/"
    size: "2Gi"
