---
global:
  TZ: "Atlantic/Reykjavik"
  puid: "1000"
  pgid: "1000"

Company: "TEST CO"

application:
  replicas: "1"
  image: "librenms/librenms:latest"
  host:
    FQDN: "nms.test.local"
    realIPfrom: "0.0.0.0/32"
    realIPheader: "X-Forwarded-For" 
    volumeSize: "20Gi"
    baseURL: ""
  logIP: "remote_addr"
  nodePort: "30080"
  uploadMAXsize: "16M"
  SNMPcommunity: 
    - "community-string-1"
    - "community-string-2"
  weathermap:
    enable: "true"
    schedule: "*/5 * * * *"
  dispatcher:
    replicas: "1"
    nodeID: "poller 1"
    args: ""
  syslogng:
    replicas: "1"
    enable: "true"
    purge: "95"
  lnms:
    graphs:
      type: "svg"
      dynamic: "true"
    billing:
      enable: "true"
      purge: "95"
      default95: "1"
    parsing:
      customers: "c"
      transit: "t"
      peering: "p"
      core: "i"
  php:
    memoryLimit: "256M"
    maxInputVars: "1000"
    opcacheMemSize: "128"
  


storage:
  path: "/opt/kubes/storage/"

## Services
mariadb:
  database: "librenms"
  volumeSize: "20Gi"
  credentials:
    rootPassword: "fooRootPassword"
    user: "foo"
    password: "bar"

msmtpd:
  host: "smtp.gmail.com"
  port: "587"
  from: "foo@gmail.com"
  credentials:
    email:
      user: "foo"
      password: "bar"   

smokeping:
  host:
    FQDN: "smokeping.test.local"

oxidized:
  enable: "true"
  host:
    FQDN: "ox.test.local"
  credentials:
    user: "deviceadmin"
    password: "devicepassword"
    token: "API-token-generated-inside-LIBRE"
