---
apiVersion: v1
kind: ConfigMap
metadata:
  name: memcached-cfg
data:
  TZ: {{ .Values.global.TZ | quote }}
  MEMCACHED_THREAD_COUNT: {{ .Values.threadCount | quote }}
  MEMCACHED_CONNECTION_REQUESTS: {{ .Values.connectionRequests | quote }}
  MEMCACHED_LOG_LEVEL: {{ .Values.logLevel | quote }}
