---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: memcached
  ports:
    - name: memcached
      protocol: TCP
      port: 11211
      targetPort: memcached

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: memcached
spec:
  serviceName: memcached
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      #hostname: {{.Release.Name}}-memcached
      restartPolicy: Always
      containers:
        - name: memcached
          image: "{{.Values.image}}"
          envFrom:
            - configMapRef:
                name: memcached
          ports:
            - name: memcached
              containerPort: 11211
