---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-memcached
spec:
  type: ClusterIP
  selector:
    app: memcached
  ports:
    - name: memcached
      protocol: TCP
      port: 11211
      targetPort: memcached

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}-memcached
  labels:
    app: memcached
spec:
  serviceName: memcached
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      hostname: {{.Release.Name}}-memcached
      restartPolicy: Always
      containers:
        - name: {{.Release.Name}}-memcached
          image: "{{.Values.image}}"
          envFrom:
            - configMapRef:
                name: memcached-cfg
          ports:
            - name: memcached
              containerPort: 11211
