---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smokeping
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  TZ: {{ .Values.global.TZ | quote }}
  PUID: {{ .Values.global.puid | quote }}
  PGID: {{ .Values.global.pgid | quote }}
