---
apiVersion: v1
kind: Service
metadata:
  name: smokeping
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  selector:
    app: smokeping
  ports:
    - name: smokeping
      protocol: TCP
      port: 8081
      targetPort: smokeping

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smokeping
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: smokeping
spec:
  serviceName: smokeping
  replicas: 1
  selector:
    matchLabels:
      app: smokeping
  template:
    metadata:
      labels:
        app: smokeping
    spec:
      restartPolicy: Always
      containers:
        - name: smokeping
          image: {{ .Values.image | quote }}
          envFrom:
            - configMapRef:
                name: smokeping
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          ports:
            - name: smokeping
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: smokeping-probes
              mountPath: /config/Probes
              subPath: Probes       
            - name: smokeping-targets
              mountPath: /config/Targets
              subPath: Targets       
            - name: application
              mountPath: /data
              subPath: smokeping/data
            - name: application
              mountPath: /config
              subPath: smokeping/config
      volumes:
        - name: application
          persistentVolumeClaim:
            claimName: application
        - name: smokeping-probes
          configMap:
            name: smokeping-probes
        - name: smokeping-targets
          configMap:
            name: smokeping-targets