---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  TZ: {{ .Values.global.TZ | quote }}
  MYSQL_ALLOW_EMPTY_PASSWORD: {{ .Values.allow_empty_password | quote }}
  MYSQL_DATABASE: {{ .Values.database | quote }}