---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cfg
data:
  TZ: {{ .Values.shared.TZ | quote }}
  MYSQL_ALLOW_EMPTY_PASSWORD: {{ .Values.mysql.allow_empty_password | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
