---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: mysql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: database
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      hostname: {{.Release.Name}}-database
      restartPolicy: Always
      containers:
        - name: database
          image: {{.Values.image}}
          args:
            - mysqld
            - --innodb-file-per-table=1
            - --lower-case-table-names=0
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          envFrom:
            - configMapRef:
                name: mysql-cfg
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_root
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_password
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: database
              mountPath: /data
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: database-claim
