apiVersion: v1
kind: Secret
metadata:
  name: mysql-sec
type: Opaque
data:
  mysql_user: {{ .Values.credentials.mysql.user | b64enc | quote }}
  mysql_password: {{ .Values.credentials.mysql.password | b64enc | quote }}
  mysql_root: {{ .Values.credentials.mysql.rootPassword | b64enc | quote }}
