apiVersion: v1
kind: Secret
metadata:
  name: mysql-sec
type: Opaque
data:
  mysql_user: {{ .Values.credentials.user | b64enc | quote }}
  mysql_password: {{ .Values.credentials.password | b64enc | quote }}
  mysql_root: {{ .Values.credentials.rootPassword | b64enc | quote }}
