---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-claim
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.storageSize }}
  volumeName: {{ .Release.Name }}-database

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-database
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    type: database
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.global.storagePath }}{{ .Release.Name }}/database
