apiVersion: v1
kind: Secret
metadata:
  name: mysql-sec
  namespace: {{ .Release.Name }}
  labels:
    version: subchart 
{{ include "common.labels" . | indent 4 }}
type: Opaque
data:
  mysql_user: {{ .Values.credentials.user | b64enc | quote }}
  mysql_password: {{ .Values.credentials.password | b64enc | quote }}
  mysql_root: {{ .Values.credentials.rootPassword | b64enc | quote }}