---
image: "oxidized/oxidized:latest"
reloadInterval: 600
hostFQDN: "ox.test.local"
enable: true
groupSupport: true
featureVers: true
reloadNodes: true
default_group: "group"

credentials:
  user: "foo"
  password: "bar"  
  token: 'ff7dd1796524fee831b52da61937d793'