---
enable: true

image: "oxidized/oxidized:latest"
replicas: "1"
reloadInterval: 600
host:
  name: "oxidized"
  FQDN: "ox.test.local"

groupSupport: true
featureVers: true
reloadNodes: true

ignore:
  types: 
    - server
    - power
  os: 
    - linux
    - windows
  groups:
    - ""
  
default_group: "core"
group:
  core:
    user: "deviceuser"
    password: "devicepassword"  
  1:
    user: ""
    password: ""
    string: "/^ox-group-1/"
  2:
    user: ""
    password: ""
    string: "/^ox-group-2/"
  3:
    user: ""
    password: ""
    string: "/^ox-group-3/"
  4:
    user: ""
    password: ""
    string: "/^ox-group-4/"
  5:
    user: ""
    password: ""
    string: "/^ox-group-5/"

credentials:
  token: 'ff7dd1796524fee831b52da61937d793'