---
enable: false

host:
  image: "loveskylark/xmatters-xa:latest"
  name: "xmatters-xa"

URL: "company.xmatters.com"
APIkey: ""
APIsecret: ""
proxy:
  auto: false
  IP: ""
  port: ""
  user: ""
  password: ""
  domain: ""
  bypass: ""
  PacFile: ""
