---
{{- if .Values.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.host.name | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  selector:
    app: {{ .Values.host.name | quote }}
  ports:
    - name: smokeping
      protocol: TCP
      port: 8081
      targetPort: smokeping

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.host.name | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: {{ .Values.host.name | quote }}
spec:
  serviceName: {{ .Values.host.name | quote }}
  replicas:  {{ .Values.host.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.host.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.host.name | quote }}
    spec:
      restartPolicy: Always
      containers:
        - name: smokeping
          image: {{ .Values.host.image | quote }}
          envFrom:
            - configMapRef:
                name: {{ .Values.host.name | quote }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          ports:
            - name: smokeping
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: smokeping-probes
              mountPath: /config/Probes
              subPath: Probes       
            - name: smokeping-targets
              mountPath: /config/Targets
              subPath: Targets       
            - name: application
              mountPath: /data
              subPath: smokeping/data
            - name: application
              mountPath: /config
              subPath: smokeping/config
      volumes:
        - name: application
          persistentVolumeClaim:
            claimName: application
        - name: smokeping-probes
          configMap:
            name: smokeping-probes
        - name: smokeping-targets
          configMap:
            name: smokeping-targets
{{- end }}
