{{- if and .Values.ingress.https .Values.ingress.letsEncrypt.enabled (not .Values.ingress.tls.existingSecretName) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ default "https-cert" .Values.ingress.tls.secretName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  secretName: {{ default "https-cert" .Values.ingress.tls.secretName | quote }}
  issuerRef:
    kind: {{ default "ClusterIssuer" .Values.ingress.letsEncrypt.issuerKind | quote }}
    name: {{ default "letsencrypt-prod" .Values.ingress.letsEncrypt.issuerName | quote }}
  commonName: {{ .Values.application.host.FQDN | quote }}
  dnsNames:
    - {{ .Values.application.host.FQDN | quote }}
{{- if .Values.smokeping.enable }}
    - {{ .Values.smokeping.host.FQDN | quote }}
{{- end }}
{{- if .Values.oxidized.enable }}
    - {{ .Values.oxidized.host.FQDN | quote }}
{{- end }}
{{- end }}
