---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms-cfg
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  TZ:                   {{ .Values.global.TZ | quote }}
  PUID:                 {{ .Values.global.puid | quote }}
  PGID:                 {{ .Values.global.pgid | quote }}
  REAL_IP_FROM:         {{ .Values.application.host.realIPfrom | quote }}
  REAL_IP_HEADER:       {{ .Values.application.host.realIPheader | quote }}
  UPLOAD_MAX_SIZE:      {{ .Values.application.uploadMAXsize | quote }}
  MEMORY_LIMIT:         {{ .Values.application.php.memoryLimit | quote }}
  OPCACHE_MEM_SIZE:     {{ .Values.application.php.opcacheMemSize | quote }}
  MAX_INPUT_VAR:        {{ .Values.application.php.maxInputVars | quote }}
  LOG_IP_VAR:           {{ .Values.application.logIP | quote }}
  INSTALL_PLUGINS:      {{ .Values.application.lnms.installPlugins | quote }}
  DB_HOST:              {{ .Values.mariadb.host.name | quote }}
  DB_NAME:              {{ .Values.mariadb.database  | quote }}
  DB_TIMEOUT:           {{ .Values.mariadb.timeout | quote }}
  REDIS_HOST:           {{ .Values.redis.lnms.host | quote }}
  REDIS_PORT:           {{ .Values.redis.lnms.port | quote }}
  REDIS_SCHEME:         {{ .Values.redis.lnms.scheme | quote }}
  REDIS_DB:             {{ .Values.redis.lnms.database | quote }}
  CACHE_DRIVER:         {{ .Values.redis.lnms.cacheDriver | quote }}
  SESSION_DRIVER:       {{ .Values.redis.lnms.sessionDriver | quote }}
  RRDCACHED_SERVER:     "{{ .Values.rrdcached.host.name }}:{{ .Values.rrdcached.host.port }}"
  ### only for testing
  #mysql_user: {{ .Values.mariadb.credentials.user | quote }}
  #mysql_password: {{ .Values.mariadb.credentials.password | quote }}
  #mysql_root: {{ .Values.mariadb.credentials.rootPassword | quote }}

{{- if .Values.xmatters.enable }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xmatters-transport-file
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  Xmatters.php: |-
{{ .Files.Get "files/Xmatters.php" | nindent 4 }}
{{- end }}

{{- if .Values.smokeping.enable }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smokeping-file
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  librenms-smokeping: |-
    /opt/librenms/lnms smokeping:generate --targets > /data/smokeping/config/librenms-targets.conf
    /opt/librenms/lnms smokeping:generate --probes  > /data/smokeping/config/librenms-probes.conf

{{- end }}

