---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.application.dispatcher.name | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: {{ .Values.application.dispatcher.name | quote }}
spec:
  serviceName: {{ .Values.application.dispatcher.name | quote }}
  replicas: {{ .Values.application.dispatcher.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.application.dispatcher.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.dispatcher.name | quote }}
    spec:
      hostname: {{ .Release.Name }}-dispatcher
      restartPolicy: Always
      containers:
        - name: {{ .Values.application.dispatcher.name | quote }}
          image: {{ .Values.application.image | quote }}
          envFrom:
            - configMapRef:
                name: librenms-cfg
          env:
            - name: DISPATCHER_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: mysql_password
            - name: DISPATCHER_ARGS
              value: {{ .Values.application.dispatcher.args | quote }}
            - name: SIDECAR_DISPATCHER
              value: "1"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
{{- if .Values.xmatters.enable }}
            - name: xmatters-transport-file
              mountPath: /opt/librenms/LibreNMS/Alert/Transport/Xmatters.php
              subPath: Xmatters.php
{{- end }}
            - name: application
              mountPath: /data
      volumes:
{{- if .Values.xmatters.enable }}
        - name: xmatters-transport-file
          configMap:
            name: xmatters-transport-file
{{- end }}
        - name: application
          persistentVolumeClaim:
            claimName: application
