---
apiVersion: batch/v1
kind: Job
metadata:
  name: depl-librenms
  namespace: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  template:
    spec:
      containers:
      - name: depl-librenms
        image: {{ .Values.application.image | quote }}
        args:
          - /bin/sh 
          - "-c"
          - |
            su librenms 
            lnms config:set device_display_default    '{{ "{{" }} $sysName_fallback }}'
            lnms config:set snmp.community            '{{ .Values.application.SNMPcommunity | toJson }}'
            lnms config:set webui.graph_type          {{ .Values.application.lnms.graphs.type | quote }}
            lnms config:set webui.dynamic_graphs      {{ .Values.application.lnms.graphs.dynamic | quote }}
            lnms config:set enable_syslog             {{ .Values.application.syslogng.enable | quote }}
            lnms config:set syslog_purge              {{ .Values.application.syslogng.purge | quote }}
            lnms config:set show_services             {{ .Values.application.lnms.services.enable | quote }}
            lnms config:set service_services_enabled  {{ .Values.application.lnms.services.enable | quote }}
            # Billing;
            lnms config:set enable_billing            {{ .Values.application.lnms.billing.enable | quote }}
            # Parsing;
            lnms config:set customers_descr.2         {{ .Values.application.lnms.parsing.customers | quote }}
            lnms config:set transit_descr.2           {{ .Values.application.lnms.parsing.transit | quote }}
            lnms config:set peering_descr.2           {{ .Values.application.lnms.parsing.peering | quote }}
            lnms config:set core_descr.2              {{ .Values.application.lnms.parsing.core | quote }}
        env:
          - name: DB_HOST
            value: {{ .Values.mariadb.host.name }}
          - name: DB_NAME 
            value: {{ .Values.mariadb.database | quote }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: mysql_user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: mysql_password
      restartPolicy: Never
  backoffLimit: 4
