---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-applicaton"
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
    spec.ingressClassName: traefik

{{- if .Values.ingress.https }}  
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    #traefik.ingress.kubernetes.io/router.middlewares: redirect-to-https@kubernetescrd
{{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
{{- end }}
spec:
  rules:
  - host: {{ .Values.application.host.FQDN | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.application.host.name }}
            port:
              number: 8000
{{- if .Values.smokeping.enable }}
  - host: {{ .Values.smokeping.host.FQDN | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smokeping
            port:
              number: 8081
{{- end }}
{{- if .Values.oxidized.enable }}
  - host: {{ .Values.oxidized.host.FQDN | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oxidized
            port:
              number: 8888
{{- end }}
  # Catch-all rule for IP access (no host specified)
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.application.host.name }}  # Main application service
            port:
              number: 8000
{{- if .Values.ingress.https }}  
  tls:
  - hosts:
    - {{ .Values.application.host.FQDN }}
{{- if .Values.smokeping.enable }}
    - {{ .Values.smokeping.host.FQDN }}
{{- end }}
{{- if .Values.oxidized.enable }}
    - {{ .Values.oxidized.host.FQDN }}
{{- end }}
    secretName: https-cert
{{- end }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: {{ .Release.Name }}  # Use the appropriate namespace
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
{{- if .Values.application.syslogng.enable }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-syslog-tcp"
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: {{ .Values.application.syslogng.name | quote }}
  ports:
    - name: syslog-tcp
      protocol: TCP
      port: 514
      targetPort: syslog-tcp

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-syslog-udp"
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: {{ .Values.application.syslogng.name | quote }}
  ports:
    - name: syslog-udp
      protocol: UDP
      port: 514
      targetPort: syslog-udp
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-snmptrapd-tcp"
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: snmptrapd
  ports:
    - name: snmptrapd-tcp
      protocol: TCP
      port: 162
      targetPort: snmptrapd-tcp

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-snmptrapd-udp"
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: snmptrapd
  ports:
    - name: snmptrapd-udp
      protocol: UDP
      port: 162
      targetPort: snmptrapd-udp
      
