---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.host.name | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  SMTP_HOST: {{ .Values.host.FQDN | quote }}
  SMTP_PORT: {{ .Values.host.port | quote }}
  SMTP_TLS: {{ .Values.TLS | quote }}
  SMTP_STARTTLS: {{ .Values.startTLS | quote }}
  SMTP_TLS_CHECKCERT: {{ .Values.TLSchecker | quote }}
  SMTP_AUTH: {{ .Values.auth | quote }}
  SMTP_FROM: {{ .Values.from | quote }}