---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msmtpd-cfg
data:
  SMTP_HOST: {{ .Values.host | quote }}
  SMTP_PORT: {{ .Values.port | quote }}
  SMTP_TLS: {{ .Values.TLS | quote }}
  SMTP_STARTTLS: {{ .Values.startTLS | quote }}
  SMTP_TLS_CHECKCERT: {{ .Values.TLSchecker | quote }}
  SMTP_AUTH: {{ .Values.auth | quote }}
  SMTP_FROM: {{ .Values.from | quote }}
