---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.host.name | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: {{ .Values.host.name | quote }}
spec:
  serviceName: {{ .Values.host.name | quote }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.host.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.host.name | quote }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.host.name | quote }}
          image: "{{.Values.image}}"
          envFrom:
            - configMapRef:
                name: {{ .Values.host.name | quote }}
          env:
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: msmtpd-sec
                  key: email_user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msmtpd-sec
                  key: email_password
