---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cfg
data:
  TZ: {{ .Values.shared.TZ | quote }}
  MYSQL_ALLOW_EMPTY_PASSWORD: {{ .Values.mysql.allow_empty_password | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cfg
data:
  TZ: {{ .Values.shared.TZ | quote }}
  REDIS_LOG_LEVEL: {{ .Values.redis.logLevel | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: memcached-cfg
data:
  TZ: {{ .Values.shared.TZ | quote }}
  MEMCACHED_THREAD_COUNT: {{ .Values.memcached.threadCount | quote }}
  MEMCACHED_CONNECTION_REQUESTS: {{ .Values.memcached.connectionRequests | quote }}
  MEMCACHED_LOG_LEVEL: {{ .Values.memcached.logLevel | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms-cfg
data:
  TZ: {{ .Values.shared.TZ | quote }}
  PUID: {{ .Values.shared.puid | quote }}
  PGID: {{ .Values.shared.pgid | quote }}
  REAL_IP_FROM: {{ .Values.shared.realIPfrom | quote }}
  REAL_IP_HEADER: {{ .Values.shared.realIPheader | quote }}
  LOG_IP_VAR: {{ .Values.shared.logIP | quote }}
  UPLOAD_MAX_SIZE: {{ .Values.shared.uploadMAXsize | quote }}
  MEMORY_LIMIT: {{ .Values.shared.MemoryLimit | quote }}
  OPCACHE_MEM_SIZE: {{ .Values.shared.opcacheMEMsize | quote }}
  DB_HOST: "{{ .Release.Name }}-database"
  DB_NAME: {{ .Values.mysql.database  | quote }}
  DB_TIMEOUT: {{ .Values.mysql.timeout  | quote }}
  REDIS_HOST: "{{ .Release.Name }}-redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  MEMCACHED_HOST: "{{ .Release.Name }}-memcached"
  MEMCACHED_PORT: "11211"
  LIBRENMS_SNMP_COMMUNITY: {{ .Values.application.SNMPcommunity | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rrdcached-cfg
data:
  TZ: {{ .Values.shared.TZ | quote }}
  PUID: {{ .Values.shared.puid | quote }}
  PGID: {{ .Values.shared.pgid | quote }}
  LOG_LEVEL: "LOG_INFO"
  WRITE_TIMEOUT: "1800"
  WRITE_JITTER: "1800"
  WRITE_THREADS: "4"
  FLUSH_DEAD_DATA_INTERVAL: "3600"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msmtpd-cfg
data:
  SMTP_HOST: {{ .Values.email.host | quote }}
  SMTP_PORT: {{ .Values.email.port | quote }}
  SMTP_TLS: "on"
  SMTP_STARTTLS: "on"
  SMTP_TLS_CHECKCERT: "on"
  SMTP_AUTH: "on"
  SMTP_USER: {{ .Values.email.user | quote }}
  SMTP_PASSWORD: {{ .Values.email.password | quote }}
  SMTP_FROM: {{ .Values.email.from | quote }}
