---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-dispatcher
  labels:
    app: dispatcher
spec:
  serviceName: dispatcher
  replicas: {{ .Values.dispatcher.replicas }}
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      hostname: {{ .Release.Name }}-dispatcher
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-dispatcher
          image: {{ .Values.dispatcher.image | quote }}
          envFrom:
            - configMapRef:
                name: librenms-cfg
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mysql_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: mysql_password
            - name: LIBRENMS_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: redis_password
            - name: DISPATCHER_NODE_ID
              value: {{ .Values.dispatcher.nodeID | quote }}
            - name: DISPATCHER_ARGS
              value: {{ .Values.dispatcher.args | quote }}
            - name: SIDECAR_DISPATCHER
              value: "1"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - name: {{ .Release.Name }}-rrdcached
              mountPath: /data
      volumes:
        - name: {{ .Release.Name }}-rrdcached
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-rrdcached-claim
