---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-librenms-config
data:
  TZ: "{{.Values.shared.TZ}}"
  PUID: "{{.Values.shared.PGUID}}"
  PGID: "{{.Values.shared.PGID}}"
  REAL_IP_FROM: "{{.Values.shared.realIPfrom}}"
  REAL_IP_HEADER: "{{.Values.shared.realIPheader}}"
  LOG_IP_VAR: "{{.Values.shared.logIP}}"
  UPLOAD_MAX_SIZE: "{{.Values.shared.uploadMAXsize}}"
  MEMORY_LIMIT: "{{.Values.shared.MemoryLimit}}"
  OPCACHE_MEM_SIZE: "{{.Values.shared.opcacheMEMsize}}"
  DB_HOST: "{{.Release.Name}}-mysql"
  DB_NAME: "{{.Release.Name}}-database"
  DB_USER: "{{.Values.credentials.mysql.user}}"
  DB_PASSWORD: "{{.Values.credentials.mysql.password}}"
  DB_TIMEOUT: "60"
  REDIS_HOST: "{{.Release.Name}}-redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  MEMCACHED_HOST: "{{.Release.Name}}-memcached"
  MEMCACHED_PORT: "11211"
  LIBRENMS_SNMP_COMMUNITY: "{{.Values.application.SNMPcommunity}}"
