---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-memcached
  labels:
    app: {{.Release.Name}}-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-memcached
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-memcached
    spec:
      containers:
        - name: {{.Release.Name}}-memcached
          image: "{{.Values.memcached.image}}"
          env:
            - name: TZ
              value: {{.Values.shared.TZ}}
      restartPolicy: Always
