---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-redis
  labels:
    app: {{.Release.Name}}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-redis
    spec:
      containers:
        - name: {{.Release.Name}}-redis
          image: {{.Values.redis.image}}
          env:
            - name: TZ
              value: {{.Values.shared.TZ}}
      restartPolicy: Always
