apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  mysql_user: {{ .Values.credentials.mysql.user | b64enc | quote }}
  mysql_password: {{ .Values.credentials.mysql.password | b64enc | quote }}
  mysql_root: {{ .Values.credentials.mysql.rootPassword | b64enc | quote }}
  librenms_user: {{ .Values.credentials.application.administrativeUser | b64enc | quote }}
  librenms_password: {{ .Values.credentials.application.administrativePassword | b64enc | quote }}
  redis_password: {{ .Values.credentials.redis.password | b64enc | quote }}
