---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-snmptrapd-service
spec:
  selector:
    app: {{.Release.Name}}-snmptrapd
  ports:
    - name: trap-tcp
      protocol: TCP
      port: 162
      targetPort: 162
    - name: trap-udp
      protocol: UDP
      port: 162
      targetPort: 162
