---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-syslogng-service
spec:
  selector:
    app: {{.Release.Name}}-syslogng
  ports:
    - name: syslog-tcp
      protocol: TCP
      port: 514
      targetPort: 514
    - name: syslog-udp
      protocol: UDP
      port: 514 
      targetPort: 514 
