---
enable: true
agent:
  enable: true
  URL: "company.xmatters.com"
  APIkey: ""
  APIsecret: ""

host:
  image: "loveskylark/xmatters-xa:latest"
  name: "xmatters"
proxy:
  auto: false
  IP: ""
  port: ""
  user: ""
  password: ""
  domain: ""
  bypass: ""
  PacFile: ""