---
{{- if .Values.enable }}
{{- if .Values.agent }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.host.name | quote }}
  namespace: {{ .Release.Name }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app: {{ .Values.host.name | quote }}
spec:
  serviceName: {{ .Values.host.name | quote }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.host.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.host.name | quote }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.host.name | quote }}
          image: {{ .Values.host.image | quote }}
          envFrom:
            - configMapRef:
                name: {{ .Values.host.name | quote }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
{{- end }}
{{- end }}