---
image: "crazymax/rrdcached"
writeThreads: "4"
writeTimeout: "1800"
writeJitter: "1800"
flushDeadDataInterval: "3600"
logLevel: "LOG_INFO"

global:
  TZ: "Europe/London"
  puid: "1000"
  pgid: "1000"